Update deploy-dev.yaml

diff --git a/.github/workflows/deploy-dev.yaml b/.github/workflows/deploy-dev.yaml
--- a/.github/workflows/deploy-dev.yaml
+++ b/.github/workflows/deploy-dev.yaml
@@ -14,6 +14,12 @@ jobs:
       TEST_VAR: ${{ vars.TEST_VAR }}
     steps:
       - name: deploy
+        id: deploy
         run: |
           echo "deployment failed! TEST_VAR=${TEST_VAR}"
-          return 1
+          exit 1
+        continue-on-error: true
+      - name: Check on failures
+        if: (${{ steps.deploy.outcome }} == 'failure')
+        run: |
+          echo "deployment failed outcome ${{ steps.deploy.outcome }}"
